version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
        name: Print
        command: echo "system print hello"

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
        name: Print
        command: echo "system print world"


  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  welcome:
    jobs:
      - print-hello
      - print-world
      - build-and-test
