version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Print
          command: echo "Hello"
      - run:
          name: Print
          command: echo "World"
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  welcome:
    jobs:
      - build-and-test
