version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "system print hello"

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "system print world"

  echo-environment:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "set and echo"
          command: |
            HoangMH1="Skyforce"
            echo $HoangMH1

  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Print
          command: echo "Hello"
      - run:
          name: Print
          command: echo "World"

      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  welcome:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - echo-environment
      - build-and-test
